\providecommand{\dd}{\,\mathrm{d}}
\providecommand{\bvec}[1]{\mathbf{#1}}
\providecommand{\bmat}[1]{\mathbf{#1}}
\providecommand{\grad}{\nabla}
\providecommand{\deriv}{\mathrm{D}}
\providecommand{\divg}{\nabla \cdot}
\providecommand{\curl}{\nabla \times}
\providecommand{\realset}{\mathbb{R}}
\providecommand{\norm}[1]{\left\|#1\right\|}
\providecommand{\abs}[1]{\left|#1\right|}
\providecommand{\jump}[1]{\left[\!\left[#1\right]\!\right]}
\providecommand{\avg}[1]{\left\{\!\left\{#1\right\}\!\right\}}